leveling:
    power: 1.03
    baseExperience: 100
    maxExperience: 90000
    maxLevel: 99
    classSwitchLevel: 20
properties:
    iConomy: false
    swapcost: 10
    prefix: 'Heroes:'
    color: 'RED'