leveling:
    power: 1.03
    baseExperience: 100
    maxExperience: 90000
    maxLevel: 99
default:
    class: 'Vagrant'
    level: 1
properties:
    iConomy: false
    swapcost: 10
    prefix: 'Heroes:'
    color: 'RED'
    