name: Heroes
main: com.herocraftonline.dev.heroes.Heroes
version: 0.0.1
website: http://www.herocraftonline.com
authors: [DThielke, Rigby, RightLegRed]
description: Experience, leveling and class system for Minecraft developed by the Herocraft coding team.
commands:
  heroes:
    aliases: ['hero']
    description: Heroes commands
    usage: /<command>
  hrecover:
    description: Heroes Recover Items command
    usage: /<command>
  p:
    description: Heroes command
    usage: /<command> <message>
  skill:
    aliases: ['hskill']
    description: Heroes command
    usage: /<command> <skill>
  hlevel:
    aliases: ['level','lvl']
    description: Display Hero level information
    usage: /<command>
  assign:
    description: Binds a skill to an item
    usage: /<command> <skill> 
  mana:
    description: Displays the hero's current mana
    usage: /<command>