name: Heroes
main: com.herocraftonline.dev.heroes.Heroes
version: 0.0.1
website: http://www.herocraftonline.com
authors: [DThielke, Rigby, RightLegRed]
description: Experience, leveling and class system for Minecraft developed by the Herocraft coding team.
commands:
  heroes:
    aliases: ['h','hero']
    description: Heroes commands
    usage: /<command>
  hrecover:
    description: Heroes Recover Items command
    usage: /<command>
  p:
    description: Heroes command
    usage: /<command> <message>
  skill:
    description: Heroes command
    usage: /<command> <skill>
  hskills:
    description: Display Hero Skills
    usage: /<command>