name: Heroes
main: com.herocraftonline.dev.heroes.Heroes
version: 0.0.1
website: http://www.herocraftonline.com
authors: [DThielke, Rigby, RightLegRed]
description: Experience, leveling and class system for Minecraft developed by the Herocraft coding team.
commands:
  heroes:
    description: Heroes commands
    usage: /heroes <command>